AllCops:
  Exclude:
    - 'Guardfile'
    - 'bin/*'
    - 'Gemfile'
    - 'Rakefile'
Documentation:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Exclude:
    - 'config/initializers/*'
    - 'config/puma.rb'
    - 'config/application.rb'
    - 'config/environments/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'db/seeds.rb'
    - 'db/schema.rb'
