Layout/AlignParameters:
  Exclude:
    - bin/*

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/schema.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - spec/**/*_spec.rb
    - db/schema.rb
    - db/migrate/*

Metrics/LineLength:
  Exclude:
    - config/initializers/content_security_policy.rb
    - config/initializers/devise.rb
    - config/environments/production.rb
    - config/application.rb
    - spec/rails_helper.rb
    - Gemfile
    - db/schema.rb
    - db/migrate/*
    - bin/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Performance/RegexpMatch:
  Exclude:
    - bin/*

Style/ExpandPathArguments:
  Exclude:
    - bin/*

Style/FrozenStringLiteralComment:
  Exclude:
    - db/schema.rb

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Layout/SpaceBeforeComma:
  Exclude:
    - db/migrate/*

Style/StringLiterals:
  Exclude:
    - db/schema.rb
    - bin/*

Style/WordArray:
  Exclude:
    - db/schema.rb
